# Generated by Django 5.1.6 on 2025-03-22 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coupon',
            name='coupon_type',
        ),
    ]
