# Generated by Django 5.1.6 on 2025-03-22 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0002_remove_coupon_coupon_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='coupon_description',
            field=models.TextField(blank=True),
        ),
    ]
