# Generated by Django 5.1.6 on 2025-03-22 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0003_coupon_coupon_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coupon',
            old_name='coupon_description',
            new_name='description',
        ),
    ]
