# Generated by Django 5.1.6 on 2025-03-26 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_category_is_disabled'),
        ('promotions', '0004_rename_coupon_description_coupon_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='applicable_categories',
            field=models.ManyToManyField(blank=True, related_name='offers', to='products.category'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='applicable_products',
            field=models.ManyToManyField(blank=True, related_name='offers', to='products.product'),
        ),
    ]
