# Generated by Django 5.1.6 on 2025-03-26 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0005_alter_offer_applicable_categories_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
