# Generated by Django 5.1.6 on 2025-03-26 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0006_offer_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='end_date',
            field=models.DateTimeField(default='2025-03-22 03:51:45'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='coupon',
            name='start_date',
            field=models.DateTimeField(default='2025-03-29 03:51:49'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='offer',
            name='end_date',
            field=models.DateTimeField(default='2025-03-22 03:51:45'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='offer',
            name='start_date',
            field=models.DateTimeField(default='2025-03-29 03:51:49'),
            preserve_default=False,
        ),
    ]
