# Generated by Django 5.1.6 on 2025-03-28 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0007_alter_coupon_end_date_alter_coupon_start_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='banner_image',
            field=models.ImageField(default='', upload_to='images/offers/'),
            preserve_default=False,
        ),
    ]
