# Generated by Django 5.1.6 on 2025-03-11 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0005_address'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'verbose_name_plural': 'Addresses'},
        ),
    ]
