# Generated by Django 5.1.6 on 2025-03-13 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0009_cart_created_at_cartitem_added_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='variant_weight',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
