# Generated by Django 5.1.6 on 2025-03-13 11:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0010_alter_cartitem_variant_weight'),
        ('products', '0010_alter_product_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='variant_weight',
        ),
        migrations.AddField(
            model_name='cartitem',
            name='variant',
            field=models.ForeignKey(default=53, on_delete=django.db.models.deletion.CASCADE, to='products.productvariant'),
            preserve_default=False,
        ),
    ]
