# Generated by Django 5.1.6 on 2025-03-22 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0014_cart_coupon_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='coupon_code',
            new_name='coupon',
        ),
    ]
