# Generated by Django 5.1.6 on 2025-03-25 03:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0017_wallet_wallettransaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='referral_key',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='wallettransaction',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed')], default='pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='wallettransaction',
            name='wallet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='customers.wallet'),
        ),
    ]
