# Generated by Django 5.1.6 on 2025-03-25 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0018_customer_referral_key_alter_wallettransaction_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='referral_key',
            field=models.CharField(blank=True, max_length=10, unique=True),
        ),
    ]
