# Generated by Django 5.1.6 on 2025-03-26 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0019_alter_customer_referral_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallettransaction',
            name='transaction_type',
            field=models.CharField(choices=[('add_money', 'Add Money'), ('payment', 'Payment'), ('refund', 'Refund'), ('cashback', 'Cashback'), ('referral', 'Referral Bonus')], max_length=10),
        ),
    ]
