# Generated by Django 5.1.6 on 2025-03-26 08:23

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0020_alter_wallettransaction_transaction_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallettransaction',
            name='transaction_id',
            field=models.UUIDField(default=uuid.UUID('fbed42a1-6883-4bdc-bba7-ce8e6c5a0b32')),
        ),
    ]
