# Generated by Django 5.1.6 on 2025-03-26 08:23

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0021_wallettransaction_transaction_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallettransaction',
            name='transaction_id',
            field=models.UUIDField(default=uuid.UUID('97e85a1c-520b-4563-8cf2-6f303b4daa64')),
        ),
    ]
