# Generated by Django 5.1.6 on 2025-03-26 08:26

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0022_alter_wallettransaction_transaction_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallettransaction',
            name='transaction_id',
            field=models.UUIDField(default=uuid.UUID('6ab55272-e765-4f4c-a899-b57987833c79'), unique=True),
        ),
    ]
