# Generated by Django 5.1.6 on 2025-03-28 08:16

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0026_subscriber_alter_wallettransaction_transaction_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallettransaction',
            name='transaction_id',
            field=models.UUIDField(default=uuid.UUID('7e9f36b5-0ad3-4e78-8482-9011b9dba404'), unique=True),
        ),
    ]
