# Generated by Django 5.1.6 on 2025-03-28 08:39

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0028_alter_wallettransaction_transaction_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallettransaction',
            name='transaction_id',
            field=models.UUIDField(default=uuid.UUID('ac49f15f-62df-4b26-9afd-2af58d7f43e2'), unique=True),
        ),
    ]
