# Generated by Django 5.1.6 on 2025-03-28 08:39

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0029_alter_wallettransaction_transaction_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallettransaction',
            name='transaction_id',
            field=models.UUIDField(default=uuid.UUID('d957d526-2b32-496a-b339-fbae2253a7de'), unique=True),
        ),
    ]
