# Generated by Django 5.1.6 on 2025-03-28 08:40

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0030_alter_wallettransaction_transaction_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallettransaction',
            name='transaction_id',
            field=models.UUIDField(default=uuid.UUID('86852276-94bb-4b3f-8a5e-b269151af249'), unique=True),
        ),
    ]
