# Generated by Django 5.1.6 on 2025-03-28 08:40

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0031_alter_wallettransaction_transaction_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallettransaction',
            name='transaction_id',
            field=models.UUIDField(default=uuid.UUID('9638644b-8a4b-4ffd-a86d-719a7f4a11c9'), unique=True),
        ),
    ]
