# Generated by Django 5.1.6 on 2025-03-28 08:40

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0032_alter_wallettransaction_transaction_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallettransaction',
            name='transaction_id',
            field=models.UUIDField(default=uuid.UUID('c74ca7c8-e20a-4392-b1d9-f9f9e21fc6cb'), unique=True),
        ),
    ]
