# Generated by Django 5.1.6 on 2025-03-29 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0034_alter_wallettransaction_transaction_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallettransaction',
            name='transaction_id',
            field=models.UUIDField(unique=True),
        ),
    ]
