# Generated by Django 5.1.6 on 2025-04-01 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0036_enquiry'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquiry',
            name='acknowledge_number',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
