# Generated by Django 5.1.6 on 2025-04-01 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0037_enquiry_acknowledge_number'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Enquiry',
            new_name='Message',
        ),
    ]
