# Generated by Django 5.1.6 on 2025-04-01 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0038_rename_enquiry_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='message',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('open', 'Open'), ('resolved', 'Resolved'), ('pending', 'Pending')], default='new', max_length=20),
        ),
    ]
