# Generated by Django 5.1.6 on 2025-04-01 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0039_message_is_read_message_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='is_read',
        ),
    ]
