# Generated by Django 5.1.6 on 2025-04-03 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0040_remove_message_is_read'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='referral_key',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
