# Generated by Django 5.1.6 on 2025-04-04 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0041_alter_customer_referral_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='referral_key',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
