# Generated by Django 5.1.6 on 2025-03-18 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_alter_payment_amount_paid_alter_payment_payment_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='payment_gateway_order_id',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
