# Generated by Django 5.1.6 on 2025-03-18 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_payment_payment_gateway_order_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='payment_gateway_order_id',
        ),
        migrations.AddField(
            model_name='order',
            name='payment_gateway_order_id',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
