# Generated by Django 5.1.6 on 2025-03-19 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_remove_payment_payment_gateway_order_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='payment_gateway_order_id',
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_provider_order_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('cash-on-delivery', 'Cash on Delivery'), ('card', 'Debit/Credit Card'), ('upi', 'UPI'), ('netbanking', 'Net Banking'), ('wallet', 'Wallet')], max_length=50),
        ),
    ]
