# Generated by Django 5.1.6 on 2025-03-19 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_remove_order_payment_gateway_order_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('cash-on-delivery', 'Cash on Delivery'), ('razorpay', 'RazorPay'), ('wallet', 'Wallet')], max_length=50),
        ),
    ]
