# Generated by Django 5.1.6 on 2025-03-21 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_returnrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('processing', 'Processing'), ('shipped', 'Shipped'), ('out_for_delivery', 'Out for Delivery'), ('delivered', 'Delivered'), ('return_requested', 'Return Requested'), ('return_approved', 'Returned Approved'), ('return_rejected', 'Returned Rejected'), ('refunded', 'Refunded'), ('cancelled', 'Cancelled')], default='Pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('initiated', 'Initiated'), ('processing', 'Processing'), ('success', 'Success'), ('failed', 'Failed')], default='Pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='returnrequest',
            name='note',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='returnrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='Pending', max_length=20),
        ),
    ]
