# Generated by Django 5.1.6 on 2025-03-25 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0016_order_order_level_discount_order_shipping_charge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('processing', 'Processing'), ('shipped', 'Shipped'), ('out_for_delivery', 'Out for Delivery'), ('delivered', 'Delivered'), ('return_requested', 'Return Requested'), ('return_approved', 'Returned Approved'), ('return_rejected', 'Returned Rejected'), ('return_received', 'Returned Recieved'), ('refunded', 'Refunded'), ('cancelled', 'Cancelled')], default='Pending', max_length=20),
        ),
    ]
