# Generated by Django 5.1.6 on 2025-03-28 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0019_payment_user_alter_payment_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='payment_type',
            field=models.CharField(choices=[('payment', 'Payment'), ('refund', 'Refund'), ('wallet_topup', 'Wallet Top-Up'), ('adjustment', 'Adjustment')], default='payment', max_length=50),
            preserve_default=False,
        ),
    ]
