# Generated by Django 5.1.6 on 2025-03-28 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0020_payment_payment_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='notes',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
