# Generated by Django 5.1.6 on 2025-03-28 10:59

from django.db import migrations


def populate_user_to_payment(apps, schema_editor):
    Payment = apps.get_model("orders", "Payment")

    for payment in Payment.objects.all():
        if payment.order and payment.order.user:  # If the payment has an order and the order has a user
            payment.user = payment.order.user
            payment.save()


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0021_payment_notes'),
    ]

    operations = [
        migrations.RunPython(populate_user_to_payment),
    ]
