# Generated by Django 5.1.6 on 2025-03-29 08:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0022_auto_20250328_1629'),
        ('promotions', '0008_offer_banner_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='coupon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='promotions.coupon'),
        ),
    ]
