# Generated by Django 5.1.6 on 2025-04-03 05:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0024_orderitem_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='returnrequest',
            name='order',
        ),
        migrations.AddField(
            model_name='returnrequest',
            name='order_item',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='returns', related_query_name='return', to='orders.orderitem'),
            preserve_default=False,
        ),
    ]
