# Generated by Django 5.1.6 on 2025-03-05 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_thumbnail_alter_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='relevance',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='quantity',
            field=models.DecimalField(choices=[(0.1, '0.1 unit'), (0.2, '0.2 unit'), (0.25, '0.25 unit'), (0.5, '0.5 unit'), (0.75, '0.75 unit'), (1, '1 unit'), (1.5, '1.5 unit'), (2, '2 unit'), (3, '3 unit'), (5, '5 unit')], decimal_places=2, max_digits=10),
        ),
    ]
