# Generated by Django 5.1.6 on 2025-03-10 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_remove_productvariant_product_product_variants_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvariant',
            name='quantity',
            field=models.DecimalField(decimal_places=2, max_digits=10, unique=True),
        ),
    ]
