# Generated by Django 5.1.6 on 2025-03-15 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_alter_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='is_disabled',
            field=models.BooleanField(default=False),
        ),
    ]
