# Generated by Django 5.1.6 on 2025-03-29 04:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_category_is_disabled'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='is_disabled',
        ),
    ]
