# Generated by Django 5.1.6 on 2025-03-29 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_alter_rating_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rating',
            old_name='star',
            new_name='rating',
        ),
    ]
